name: ArmorCode

env:
  product: Juiceshop
  subProduct: IoT APP
  environment: Production
  token: ${{11770924-d7a8-42ec-acf9-2cd00d2586cd}}
  buildTool: GITHUB_ACTIONS
  buildNumber: ${{github.run_number}}
  end: 30
  
on:
  # Triggers the workflow on push request events
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    # ArmorCode Validation Step
    steps:
      - name: ArmorCode Validation
        run: |
          wget https://app.armorcode.com/static/scripts/slastatus.sh
          sh slastatus.sh
